### ISSUE TITLE
[FE] Post List Compoment

### ISSUE THREAD

**Issue by truongduchuy910** [itoa-vn/docs#11]
### What
- Phát triển giao diện danh sách bài viết (ví dụ danh sách bài viết hiển thị ra khi mình tìm kiếm). Bài viết đơn lẻ đã phát triển tại https://github.com/itoa-vn/docs/pull/12. (components/Post/Item/Shorten.js)
- Yêu cầu hiển đặt file đúng vị trí. components/Post/**List**/Simple.js
- Danh sách bài viết là tập hợp từng bài viết tại (components/Post/Item/Shorten.js) tức là `import Post from components/Post/Item/Shorten.js` và `post.map(post => <Post...`

### Why
- None

### How
- Xử dụng React tuần chưa cần Apply framework vào
- Hiển thị ở trang chủ trang pages/bai-viet.js
 
> Quy trình https://github.com/itoa-vn/docs/blob/main/docs/guide/task-life-cycle.md
> Chuyển qua Analysis để phân tích, sau đó chuyển qua Reviewing để đợi xác nhận. điền thời gian đã bỏ ra để Analysis và gắn cho @truongduchuy910

**Comment by huynhtrunghieu2000** [comment]
Cái này mình nên làm kiểu 
![image](https://user-images.githubusercontent.com/27915489/154991336-f7446c1f-a2db-4d4e-a5b5-eb56ea2efca3.png)
Hay là làm theo kiểu thông thường, show ra page có list đấy nhỉ @truongduchuy910

**Comment by truongduchuy910** [comment]
@huynhtrunghieu2000  cái này chưa biết cụ thể dùng ở đâu:
- kết quả tìm kiếm bài viết.
- bài viết vừa xem, liên quan,...
Để coi cần thiết không hẳn làm nha!
