### ISSUE TITLE
[BE] File read API

### ISSUE THREAD

**Issue by truongduchuy910** [itoa-vn/docs#4]
### What

- API đọc nội dung từ file markdown thông qua tham số trong API
- Yêu cầu sử dụng GraphQL như API đọc cây thư mục.

### Why

- Hiển thị file markdown ra website

### How

Tham khảo đọc file: Example https://github.com/vercel/next.js/blob/canary/examples/blog-starter/lib/api.js

Có thể tách làm 2 pull nhỏ là pull phát triển Graphql và trả về kết quả cố định. Và pull trả về kết quả thật theo tham số truyền vào.

**Comment by buihuongquynh** [comment]
task này em làm như pull hồi chiều là đc chưa a
